#!/usr/bin/env python3
"""Generate registry documentation from the live FairLMs registries.

The point of this script is the claim it lets you make in the paper: the
registry tables in the docs are generated from the registries themselves and
cannot drift from the code. Run it in CI with --check so a stale table fails
the build.

    python scripts/gen_registry_docs.py            # write
    python scripts/gen_registry_docs.py --check    # fail if out of date

Every attribute read below is one that actually exists on the objects:
``FairnessMetric`` declares ``name``, ``bias_type`` and ``architectures``;
``DatasetDiagnostic`` declares ``name`` and annotates its ``compute`` evidence
parameter; loaders are ``FairnessDataset`` subclasses exported from
``fairlms.datasets``.
"""

from __future__ import annotations

import argparse
import inspect
import sys
from pathlib import Path

DOCS = Path(__file__).resolve().parents[1] / "docs" / "registry"

HEADER = (
    "<!-- GENERATED BY scripts/gen_registry_docs.py: DO NOT EDIT BY HAND -->\n\n"
)


def _fmt(seq) -> str:
    if not seq:
        return "n/a"
    if isinstance(seq, str):
        return f"`{seq}`"
    return ", ".join(f"`{s}`" for s in seq)


def _summary(obj) -> str:
    """First sentence of a docstring, on one line."""
    doc = inspect.getdoc(obj) or ""
    first = doc.strip().split("\n\n")[0].replace("\n", " ").strip()
    return first or "n/a"


def _aliases() -> dict:
    """Map class -> short alias exported alongside it (CPS, AUL, DisCo, ...)."""
    import fairlms.metrics as M

    out = {}
    for name in M.__all__:
        obj = getattr(M, name, None)
        if not inspect.isclass(obj):
            continue
        # An alias is a second public name bound to a class whose own __name__
        # differs from the exported name.
        if obj.__name__ != name:
            out.setdefault(obj, []).append(name)
    return out


def metrics_page() -> str:
    from fairlms.metrics import METRIC_REGISTRY

    aliases = _aliases()
    rows = []
    for name, cls in sorted(METRIC_REGISTRY.items()):
        rows.append(
            "| `{name}` | `{cls}` | {alias} | {bias} | {arch} | {task} |".format(
                name=name,
                cls=cls.__name__,
                alias=_fmt(sorted(aliases.get(cls, ()))),
                bias=f"`{cls.bias_type}`" if cls.bias_type else "n/a",
                arch=_fmt(cls.architectures),
                task=_fmt(cls.required_task),
            )
        )
    n_free = sum(1 for c in METRIC_REGISTRY.values() if c.required_task is None)

    return (
        HEADER
        + "# Metrics\n\n"
        + f"{len(rows)} registered metrics. Instantiate any of them by registry "
        "name with `fairlms.metrics.get_metric(name)`, or import the class "
        "directly. Every metric exposes "
        "`compute(model, data) -> MetricResult`.\n\n"
        "`bias_type` and `architectures` document where a metric sits in the "
        "taxonomy. **`required_task` is enforced**: it names the head the "
        "checkpoint must be loaded with, and a mismatch is refused before the "
        "metric runs rather than surfacing as a missing attribute or as "
        "numbers read off an untrained head. See "
        "[Models](../api/models.md).\n\n"
        f"The {n_free} metrics with no required task score precomputed "
        "predictions, call an API, or take a plain callable, so they impose no "
        "requirement on how a model was loaded.\n\n"
        "| Registry name | Class | Alias | Bias type | Architectures | Required task |\n"
        "|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n"
    )


def loaders_page() -> str:
    """Loaders are FairnessDataset subclasses exported from fairlms.datasets.

    There is no separate loader registry; the public export list *is* the
    registry, so this table is derived from it.
    """
    import fairlms.datasets as DS
    from fairlms.datasets import FairnessDataset

    rows = []
    for name in sorted(DS.__all__):
        cls = getattr(DS, name)
        if not (
            inspect.isclass(cls)
            and issubclass(cls, FairnessDataset)
            and cls is not FairnessDataset
        ):
            continue
        src = inspect.getsource(inspect.getmodule(cls))
        if "load_dataset(" in src:
            origin = "Hugging Face Hub, downloaded at first use"
        else:
            origin = "bundled with the package"
        params = [
            p
            for p in inspect.signature(cls.__init__).parameters
            if p not in ("self",)
        ]
        rows.append(
            "| `{name}` | {summary} | {origin} | {params} |".format(
                name=name,
                summary=_summary(cls),
                origin=origin,
                params=_fmt(params),
            )
        )

    return (
        HEADER
        + "# Loaders\n\n"
        + f"{len(rows)} dataset loaders behind one interface: each subclasses "
        "`FairnessDataset` and exposes `load()`, returning examples that a "
        "metric's `data` argument accepts directly.\n\n"
        "Each benchmark retains its own license. Two are bundled with the "
        "package (CrowS-Pairs, BBQ); the rest are fetched from the Hugging "
        "Face Hub on first use.\n\n"
        "| Loader | Description | Data origin | Constructor arguments |\n"
        "|---|---|---|---|\n" + "\n".join(rows) + "\n"
    )


def diagnostics_page() -> str:
    from fairlms.diagnostics import DIAGNOSTIC_REGISTRY

    rows = []
    for name, cls in sorted(DIAGNOSTIC_REGISTRY.items()):
        evidence = inspect.signature(cls.compute).parameters.get("evidence")
        ann = getattr(evidence, "annotation", None)
        ann = ann if isinstance(ann, str) else getattr(ann, "__name__", "n/a")
        rows.append(
            "| `{name}` | `{cls}` | `{ev}` | {summary} |".format(
                name=name, cls=cls.__name__, ev=ann, summary=_summary(cls)
            )
        )

    return (
        HEADER
        + "# Diagnostics\n\n"
        + f"{len(rows)} registered components. Each reports one of `ready`, "
        "`blocked`, `not_applicable`, `failed`. Unavailable evidence is never "
        "reported as a measured zero.\n\n"
        "Diagnostics consume explicit evidence objects and a "
        "`DatasetAuditSpec`, never a model. Run them through "
        "`audit_representativeness` or `audit_scores`.\n\n"
        "| Component | Class | Evidence | Description |\n|---|---|---|---|\n"
        + "\n".join(rows)
        + "\n"
    )


#: Ordered as the book chapter presents the intervention categories.
_CATEGORY_BLURB = {
    "pre": "Applied to the data before training. Transform evidence, not models.",
    "in": "Loss components composable with a normal training loop. These return "
    "a callable objective, never a trained model: there is no trainer in the "
    "core package.",
    "intra": "Edits to a loaded model. Each returns a `ModelAdapter`, so any "
    "metric re-evaluates the mitigated model without modification.",
    "post": "Decision rules fitted on outputs. Serializable, and applied "
    "without the model that produced the scores.",
}


def mitigation_page() -> str:
    from fairlms.mitigation import MITIGATOR_REGISTRY

    sections = []
    for category, blurb in _CATEGORY_BLURB.items():
        rows = []
        for name, cls in sorted(MITIGATOR_REGISTRY.items()):
            if cls.category != category:
                continue
            rows.append(
                "| `{name}` | `{cls}` | {access} | {arch} | {req} | {acc} |".format(
                    name=name,
                    cls=cls.__name__,
                    access=f"`{cls.access}`",
                    arch=_fmt(sorted(cls.architectures)),
                    req=_fmt(sorted(cls.requires)) if cls.requires else "-",
                    acc=_fmt(sorted(t.__name__ for t in cls.accepts)),
                )
            )
        sections.append(
            f"## {category.capitalize()}-processing\n\n{blurb}\n\n"
            "| Component | Class | Access | Architectures | Requires | Accepts |\n"
            "|---|---|---|---|---|---|\n" + "\n".join(rows) + "\n"
        )

    return (
        HEADER
        + "# Mitigators\n\n"
        + f"{len(MITIGATOR_REGISTRY)} registered components. Each declares an "
        "intervention category, an access level, supported architectures, the "
        "capabilities it needs from a model, and the evidence containers it "
        "consumes. Applicability is decided from those declarations by the same "
        "matcher the metrics use, and an unsatisfiable pairing is refused by "
        "name.\n\n"
        "Access levels are ordered `black_box` < `gray_box` < `white_box`; a "
        "component declares the **minimum** it needs.\n\n"
        + "\n".join(sections)
        + "\n## Not provided\n\n"
        "Named in the paper as extension points and deliberately absent from "
        "this registry: RLHF, DPO, Constitutional AI and other "
        "preference-optimized training loops; UniDetox; the "
        "influence-estimation half of IF-Guide; GeDi, RAD, DExperts, FairSteer, "
        "ARGRE and other guided-decoding methods; LSDM; FairMed; "
        "gender-constrained beam search; model-based rewriting.\n\n"
        "Named in the book chapter but not provided here, recorded so that a "
        "reader comparing the two does not mistake omission for oversight: "
        "conceptor debiasing; pruning and ablation; the no-attribute "
        "(name-proxy) setting; Co2PT; BiasUnlearn; data filtering and toxicity "
        "removal; dataset curation and balanced collection; output filtering "
        "and safety classification; refusal policies and content moderation; "
        "counterfactual data *substitution*. The book's bias diagnosis and data "
        "auditing family is covered, but by the "
        "[diagnostics](diagnostics.md) layer.\n"
    )


PAGES = {
    "metrics.md": metrics_page,
    "loaders.md": loaders_page,
    "diagnostics.md": diagnostics_page,
    "mitigation.md": mitigation_page,
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if pages are stale")
    args = ap.parse_args()

    DOCS.mkdir(parents=True, exist_ok=True)
    stale = []

    for filename, builder in PAGES.items():
        path = DOCS / filename
        new = builder()
        if args.check:
            old = path.read_text() if path.exists() else ""
            if old != new:
                stale.append(filename)
        else:
            path.write_text(new)
            print(f"wrote {path}")

    if stale:
        print("STALE (run scripts/gen_registry_docs.py): " + ", ".join(stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
